name: docs ⚙️

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths:
      - 'docs/**'
  release:
    types:
      - released

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v5
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements 📦
      run: |
        pip3 install .
        pip3 install ".[dev]"
    - name: build docs 🏗️
      run: cd docs && make html
